name: Construction Project Classification CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  DAGSHUB_USERNAME: ${{ secrets.DAGSHUB_USERNAME }}
  DAGSHUB_TOKEN: ${{ secrets.DAGSHUB_TOKEN }}

jobs:

  train-and-log:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Preprocessing
        run: |
          python preprocessing/preprocess.py

      - name: Train Model 
        env:
          MLFLOW_TRACKING_URI: https://dagshub.com/nabilasasa066/mlops-konstruksi.mlflow/
          MLFLOW_TRACKING_USERNAME: ${{ secrets.DAGSHUB_USERNAME }}
          MLFLOW_TRACKING_PASSWORD: ${{ secrets.DAGSHUB_TOKEN }}
        run: |
          python Workflow-CI/MLProject/modelling.py \
            --data_path Membangun_model/data_konstruksi_preprocessed/preprocessed.csv \
            --n_estimators 100 \
            --max_depth 10 \
            --min_samples_split 2

      # =========================
      # SAVE MODEL ARTIFACT
      # =========================
      - name: Upload Model Artifact
        uses: actions/upload-artifact@v4
        with:
          name: trained-model
          path: outputs/model_proyek.pkl